on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
      - name: checking versions
        run: node --version
        run: npm --version
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm install

      - name: Generate build
        runs: num run build

      - name: Upload release
        uses: actions/upload-artifact@v2
        with:
          name: bot-release
          path: out/
